project:
  type: website

website:
  title: "Introduction to Biostatistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: material.qmd
        text: Material
      - href: homework.qmd
        text: Homework
      - href: readings.qmd
        text: Readings

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

