project:
  type: website

website:
  title: " BMS510 - Biostatistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: material.qmd
        text: Material
      - href: homework.qmd
        text: Homework
      - href: readings.qmd
        text: Readings
      - href: https://dnzmarcio.github.io/personal_webpage/
        text: Back to marciodiniz.info
      


format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    
execute:
  freeze: auto
  link-external-newwindow: true

