---
title: "Introduction to Biostatistics"
format: 
  html:
    toc: true
---

The website is an archive for the material that was originally created for the BMS510 - Biostatistics course offered in the Ph.D. program in Biomedical Sciences at Cedars-Sinai Medical Center from 2016 to 2022. It has received contributions from several colleagues along of the years, in special, André Rogatko, Quanlin-Li and Michael Luu.

I have received the [David L. Rimoin Teaching Excellence Award](https://www.cedars-sinai.edu/research/news/cedars-science/2021/commencement-celebrates-two-classes.html) for Class of 2020 and 2021 as a results of these efforts.

# Lectures on Statistical Concepts

Every living organism in the universe gathers information from the environment and makes decisions. Good decisions are rewarded with survival. Statistical science main objects of study are how to summarize, interpret information and make decisions. This places statistics in the core of all sciences. - André Rogatko

The goal of this module is to introduce fundamental probability and statistical concepts used to design and analyze studies and experiments. You will learn how your opinion should change on the basis of data; how to estimate values of interest; what uncertainty is attached to these values; how to improve the efficiency of your investigations; and how your imperfect information should be used to make decisions for action. The preferred approach will be by presenting motivating case studies.

# Hands on Statistical Programming with R

R is a language and environment for statistical computing and graphics. R provides a wide variety of statistical (e.g., classical statistical tests, Bayesian analysis, linear modelling) and graphical techniques, and is highly extensible. The S language is often the vehicle of choice for research in statistical methodology, and R provides an Open Source route to participation in that activity.

One of R’s strengths is the ease with which well-designed publication-quality plots can be produced, including mathematical symbols and formulae where needed. Great care has been taken over the defaults for the minor design choices in graphics, but the user retains full control.

R is available as Free Software under the terms of the Free Software Foundation’s GNU General Public License in source code form. It compiles and runs on a wide variety of UNIX platforms and similar systems (including FreeBSD and Linux), Windows and MacOS.

# Learning Objectives

All students completing the Biostatistics Course are expected to have acquired the following knowledge and skills on:
1.	How statistical methods play a fundamental role in reproducibility in science;

2.	How to critically read statistical components of scientific papers;

3.	How to manage and describe experimental data;

4.	How to make decisions and interpret results of statistical analyses;

5.	How to interact with statisticians.

# Instructors

Marcio A. Diniz - marcio.diniz@mountsinai.org

Michael Luu - michael.luu@cshs.org

# Useful links

1.	http://www.nature.com/collections/qghhqm/
2.	http://www.ats.ucla.edu/stat/
3.	http://r4ds.had.co.nz/

